"""! @file

# Test Documentation

TODO_DOC


## Classes
	* test_class


[generated by Auto Code Commenter at 2022-03-14 15:39:03. https://github.com/drbsmith/auto_code_commenter]
@package test """


class test_class():
	def __init__(self, a, b, c):
		self.a = b
		self.b = c
		self.c = a # rotates assignment to the previous variable

		print('test_class initialized.')

	def coolFunction(self, # needless commentary in the middle of a function definition!
		d ):
		print('returning what I got, a {}'.format(d))
		return d







	print('goodbye!')
