"""! @file

# Config

TODO_DOC


## Functions
	* GetGlobalConfig

[generated by Auto Code Commenter at 2022-03-02 16:27:14. https://github.com/drbsmith/auto_code_commenter]
@package util"""


import os, json

def GetGlobalConfig(filename='../acc_config.json'):
	import errno

	if not os.exists(filename):
		raise FileNotFoundError(errno.ENOENT, os.sterror(errno.ENOENT), filename)

	with open(filename, 'r') as f:
		ret = json.load(f)

	return ret