"""! @file

# Config

TODO_DOC


## Functions
	* GetGlobalConfig

[generated by Auto Code Commenter at 2022-03-02 16:27:14. https://github.com/drbsmith/auto_code_commenter]
@package util"""


import os, json

def GetGlobalConfig(filename='./acc_config.json'):
	"""!
	TODO_DOC
	
	@param filename='../acc_config.json': TODO_DOC
	@return TODO_DOC
	
	## Profile
	* line count: 7
	* characters: 229
	* imports: import errno
	* returns: ret
	"""
	
	import errno

	if not os.path.isfile(filename):
		raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), filename)

	with open(filename, 'r') as f:
		ret = json.load(f)

	return ret
