"""! @package src/sql_databases 

# Package: src/sql_databases

Trying a few things:
* autogenerating 2 tables for each sql table/view: one is a reduced, overview of each column and the second is the full information_schema read out
* a way for the human written documentation for certain tables and columns to exist in other files, and this module reads through it and merges the manual documentation with the auto-gen docs.

## Entry points:

* in src/ look for document_database.py

## Modules

* postgres_utils.py
* connector.py
* make_database_md.py
* mysql_utils.py

[generated by Auto Code Commenter at 2022-03-27 11:44:18. https://github.com/drbsmith/auto_code_commenter]

"""