"""! @file

# Parse This

TODO_DOC

## Classes
	* myclass

## Functions
	* GlobalFunc

[generated by Auto Code Commenter at 2022-03-08 16:24:24. https://github.com/drbsmith/auto_code_commenter]
@package test"""


import os
import sys

DEBUG = False

@decorator
class myclass():

	@classmethod
	def function1():
		# function 1 comment:
		y = "abcde"

		def inner_function(x):
			if '#' in x:
				while '#' in x:
					x.replace('#', '%')

			return x

		return inner_function(y)

	def __init__(self, a):
		y = a

def GlobalFunc(arg, kwarg=None):
	pass
if __name__ == '__main__':
	y = myclass('xy#z')

