"""! @package ./src 

# Package: ./src

# Package: src

The primary source package for the Auto Code Commenter

## Modules

* variable_documenter.py
* function_profiler.py
* test_documentation.py
* directory_check_for_headers.py
* init_file_creator.py
* py_parsers.py
* header_generator.py
* function_documenter.py

[generated by Auto Code Commenter at 2022-03-14 15:15:10. https://github.com/drbsmith/auto_code_commenter]

"""